on:
  push:
    branches:
      - main
      - master
      - devel

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Systeme dependences
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Install package
        run: |
          install.packages("curl")
          install.packages("pkgcache") 
          install.packages("pkgdepends")
          install.packages("pkgdown")
          library("pkgdepends")
          install.packages("pak")
          pak::local_install()
        shell: Rscript {0}

      - name: Codecov analysis
        run: |
          install.packages("covr")
          library("covr")
          codecov()
        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
